### ISSUE TITLE
Formatting with standardrb

### ISSUE THREAD

**Issue by rkapu** [bekicot/solargraph-standardrb#8]
Hi! Thank you for the plugin! Works wonderfully with neovim lsp.

Is there any news on formatting with standardrb from solargraph?
Because currently when executing lsp formatting, solargraph is formatting file with rubocop rules.

I saw this issue on solargraph repo so I guess that formatting still isn't implemented, right?
https://github.com/castwide/solargraph/issues/307

**Comment by dimanyc** [comment]
+1 seeing the same issue with Vim 8.2 and coc-nvim . 

#### EDIT: 
one workaround I found is to copy standard's rubocop rules for your Ruby version and append them as your local `.rubocop.yml`. Not ideal, but it does the trick.

And, of course, huge thanks for this awesome gem!

**Comment by bekicot** [comment]
AFAIK solargraph doesn't have formatter yet. It is better for you guys to use rubocop with `inherited_gem` feature.

https://github.com/bekicot/solargraph-standardrb/issues/5#issuecomment-987682946

**Comment by rkapu** [comment]
@bekicot Thanks!
Works good using `inherited_gem` feature.
